name: Build and Push to Dockerhub

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Download EarnApp installer
        run: wget -qO- https://brightdata.com/static/earnapp/install.sh > ./earnapp.sh

      - name: Get version
        run: grep VERSION= ./earnapp.sh | cut -d'"' -f2 > ./version

      - name: Build & Push - Latest Gost
        run: |
          docker buildx build --squash --push \
          -t madereddy/earnapp:$(cat ./version) \
          -t madereddy/earnapp:latest \
          --platform linux/amd64,linux/arm64 build/gost
